services:
  backend:    
    image: ghcr.io/gdavidev/emuhub-backend:latest
    env_file:
      - .env
    ports:
      - "5000:8080"
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      Token__Secret: ${TOKEN_SECRET}
      Token__Issuer: ${TOKEN_ISSUER}
      Token__Audience: ${TOKEN_AUDIENCE}
      ConnectionStrings__Default: Host=${DATABASE_SERVER};Database=${DATABASE_NAME};Username=${DATABASE_USER_ID};Password=${DATABASE_PASSWORD}
      Minio__Endpoint: ${MINIO_ENDPOINT}
      Minio__AccessKey: ${MINIO_ACCESS_KEY}
      Minio__SecretKey: ${MINIO_SECRET_KEY}
      Mailing__Smtp__Server: ${MAILING_SMTP_SERVER}
      Mailing__Smtp__Port: ${MAILING_SMTP_PORT}
      Mailing__Sender: ${MAILING_SENDER}
      Mailing__Key: ${MAILING_KEY}
    restart:
      unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
      - minio-network
    command: >
      bash -c "
        /app/wait-for-it.sh $${DATABASE_SERVER}:5432 --timeout=30 --
        /app/wait-for-it.sh $${MINIO_ENDPOINT} --timeout=30 --
        dotnet /app/Emuhub.API.dll"

  frontend:
    image: ghcr.io/gdavidev/emuhub-frontend:latest
    restart:
      unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - backend

networks:
  app-network:
    external: true
  minio-network:
    external: true