services:
  backend:
    build:
      context: ./backend    
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-Release}  # Default to Release
      target: ${TARGET_STAGE:-production}  # Default to production
    env_file:
      - .env
    ports:
      - "5000:8080"
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}   
      Token__Secret: ${TOKEN_SECRET}
      Token__Issuer: ${TOKEN_ISSUER}
      Token__Audience: ${TOKEN_AUDIENCE}
      ConnectionStrings__Default: Server=${DATABASE_SERVER};Database=${DATABASE_NAME};User ID=${DATABASE_USER_ID};Password=${DATABASE_PASSWORD};TrustServerCertificate=True
      Minio__Endpoint: ${MINIO_ENDPOINT}
      Minio__AccessKey: ${MINIO_ACCESS_KEY}
      Minio__SecretKey: ${MINIO_SECRET_KEY}
    restart: 
      unless-stopped
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - app-network
      - minio-network
    command: >
      bash -c "
          /app/wait-for-it.sh $${DATABASE_SERVER}:1433 --timeout=30 --
          /app/wait-for-it.sh $${MINIO_ENDPOINT} --timeout=30 --
          dotnet Emuhub.API.dll"

  frontend:
    build:
      context: ./webapp
      target: ${TARGET_STAGE:-production}  # Default to production
    restart: 
      unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - backend

networks:
  app-network:
    external: true
  minio-network:
    external: true