version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - minio

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # Web UI
      - "9001:9001" # API
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234
    volumes:
      - ./minio-data:/data
    command: server --console-address ":9000" /data
