services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - .:/src
      - ~/.aspnet/https:/root/.aspnet/https:ro
    ports:
      - "5000:5000" # HTTP port
      - "5001:5001" # HTTPS port
      - "4020:4020" # remote debugger port
    command: >
        /src/wait-for-it.sh ${DATABASE_SERVER}:1433 --timeout=30 --
        /src/wait-for-it.sh ${MINIO_ENDPOINT} --timeout=30 --
        dotnet watch run --no-launch-profile --project Emuhub.API/Emuhub.API.csproj

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sqlserver-data:/var/opt/mssql

  minio:
    volumes:
      - ./minio-data:/data
      