services:
  postgres:
    container_name: postgres
    env_file:
      - .env
    networks:
      - app-network
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER_ID}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    command:
      [
        "postgres",
        "-c", "shared_buffers=128MB",
        "-c", "work_mem=4MB",
        "-c", "maintenance_work_mem=64MB",
        "-c", "max_connections=20",
        "-c", "effective_cache_size=384MB"
      ]

  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    restart: 
      unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    networks:
      - minio-network

networks:
  app-network:
    name: app-network
  minio-network:
    name: minio-network

volumes:
  db-data:
  minio-data:  