//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emuhub.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessagesResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessagesResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Emuhub.Exceptions.ExceptionMessagesResource", typeof(ExceptionMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        public static string CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        public static string EMULATOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("EMULATOR_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string FIELD_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("FIELD_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        public static string FIELD_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("FIELD_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        public static string FIELD_CANNOT_BE_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("FIELD_CANNOT_BE_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        public static string FILE_EXTENSION_MUST_BE {
            get {
                return ResourceManager.GetString("FILE_EXTENSION_MUST_BE", resourceCulture);
            }
        }
        
        public static string FILE_MUST_HAVE_EXTENSION {
            get {
                return ResourceManager.GetString("FILE_MUST_HAVE_EXTENSION", resourceCulture);
            }
        }
        
        public static string GAME_NOT_FOUND {
            get {
                return ResourceManager.GetString("GAME_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string ID_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("ID_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        public static string MINIMUN_LENGTH {
            get {
                return ResourceManager.GetString("MINIMUN_LENGTH", resourceCulture);
            }
        }
        
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string NEGATIVE_PAGE_NUMBER {
            get {
                return ResourceManager.GetString("NEGATIVE_PAGE_NUMBER", resourceCulture);
            }
        }
        
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        public static string PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
